#ifndef TREASURE_DATA_TYPES_H
#define TREASURE_DATA_TYPES_H

#include "TreasureDataTypes.h"

class TreasureDataTypes
{
public:
    enum TreasureImageID
    {
        TREASURE_CARD_UNKNOWN = 0,

        TREASURE_CARD_NOTHING,

        TREASURE_CARD_POISON,

        TREASURE_CARD_TRAP_WALL,
        TREASURE_CARD_TRAP_PIT,

        TREASURE_CARD_ROAMING_MONSTER,

        TREASURE_CARD_GOLD,
        TREASURE_CARD_JEWELS,
        TREASURE_CARD_GEMSTONE,
        TREASURE_CARD_GOLD_TREASURE,

        TREASURE_CARD_BRAVENESS_POTION,
        TREASURE_CARD_HEALING_POTION,
        TREASURE_CARD_HOLY_WATER,
        TREASURE_CARD_IMMUNIZATION_POTION,
        TREASURE_CARD_MAGIC_POTION,
        TREASURE_CARD_PHILOSOPHERS_STONE,
        TREASURE_CARD_POWER_POTION,
        TREASURE_CARD_RESISTANCE_POTION,
        TREASURE_CARD_SPRINT_POTION,
    };

};

#endif
